version : 0.0.2
container-name-run : "{{#toLowerCase appName}}{{/toLowerCase}}"
container-name-tools : "bx-dev-{{#toLowerCase appName}}{{/toLowerCase}}-tools"
image-name-run : "{{#toLowerCase appName}}{{/toLowerCase}}"

{{#has buildType 'maven'}}
image-name-tools : "bx-dev-java-maven-tools"
host-path-run : "target"
build-cmd-run : "mvn install -Dmaven.repo.local=/project/.m2/repository"
test-cmd : "mvn install -Dmaven.repo.local=/project/.m2/repository"
build-cmd-debug : "mvn install -Dmaven.repo.local=/project/.m2/repository"
{{/has}}
{{#has buildType 'gradle'}}
image-name-tools : "bx-dev-java-gradle-tools"
host-path-run : "build"
build-cmd-run : "gradle -g . build"
test-cmd : "gradle -g . build"
build-cmd-debug : "gradle -g . build"
{{/has}}

container-path-run : "/project"
container-path-tools : "/project"

{{#has frameworkType 'liberty'}}
#Liberty server settings
container-port-map : "9080:9080,9443:9443"
container-port-map-debug : "7777:7777"
debug-cmd : "server debug"
{{/has}}

{{#has frameworkType 'spring'}}
#Tomcat/Spring settings
container-port-map : "8080:8080,8443:8443"
container-port-map-debug : "7777:7777"
run-cmd : "java -Dspring.profiles.active=local -jar {{appName}}-{{version}}.jar"
{{/has}}

dockerfile-run : "Dockerfile"
dockerfile-tools : "Dockerfile-tools"
