language: java
jdk:
  - oraclejdk8
before_install:
  - wget http://services.gradle.org/distributions/gradle-3.5-bin.zip
  - shasum -a 256 -c ./sha256.txt
  - unzip -qq gradle-3.5-bin.zip
  - export GRADLE_HOME=$PWD/gradle-3.5
  - export PATH=$GRADLE_HOME/bin:$PATH
  - gradle -v
  - nvm install 6.9.1
  - cd ./generator-java
  - npm i -g makeshift && makeshift -r https://registry.npmjs.org
  - npm install
script:
  - ../build.sh
  - ../deploy.sh
# Pull request builds and push builds only run when the target branch is one of these:
branches:
  only:
    - master
