apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: "{{tag '  .Chart.Name '}}-deployment"
  labels:
    chart: "{{tag ' .Chart.Name '}}-{{{tag ' .Chart.Version | replace "+" "_" '}}}"
spec:
  replicas:  {{tag ' .Values.replicaCount '}}
  revisionHistoryLimit: {{tag ' .Values.revisionHistoryLimit '}}
  template:
    metadata:
      labels:
        app: "{{tag '  .Chart.Name '}}-selector"
    spec:
     containers:
      - name: {{tag '  .Chart.Name  '}}
        image: "{{tag ' .Values.image.repository '}}{{tag ' .Values.image.name '}}:{{tag ' .Values.image.tag '}}"
        imagePullPolicy: {{tag ' .Values.image.pullPolicy '}}        
        readinessProbe:
          httpGet:
          path: /{{appName}}/health
            port: 9080
          initialDelaySeconds: 20
