container-name-run : "{{appName}}"
container-name-tools : "{{appName}}-tools"

{{#has buildType 'maven'}}
host-path-run : "target"
build-cmd-run : "mvn install"
test-cmd : "mvn install"
build-cmd-debug : "mvn install"
{{/has}}
{{#has buildType 'gradle'}}
host-path-run : "build"
build-cmd-run : "gradle build"
test-cmd : "gradle build"
build-cmd-debug : "gradle build"
{{/has}}

container-path-run : "/project"
container-path-tools : "/project"

container-port-map : "9080:9080,9443:9443"
container-port-map-debug : "7777:7777"

dockerfile-run : "Dockerfile"
dockerfile-tools : "Dockerfile-tools"
image-name-run : "{{#toLowerCase appName}}{{/toLowerCase}}"
image-name-tools : "javaclitools"

run-cmd : "server run"
debug-cmd : "server debug"
stop-cmd : "server stop"
