container-name-run : "{{appName}}"
container-name-tools : "{{appName}}-tools"

{{#maven}}
host-path-run : "target"
{{/maven}}
{{#gradle}}
host-path-run : "build"
{{/gradle}}

container-src-path : "/project"
container-path-tools : "/project"

container-port-map : "9080:9080,9443:9443"
container-port-map-debug : "7777:7777"

dockerfile-run : "Dockerfile-run"
dockerfile-tools : "Dockerfile-tools"
image-name-run : "{{appName}}"
image-name-tools : "javaclitools"

{{#maven}}
build-cmd-run : "mvn install"
test-cmd : "mvn install"
build-cmd-debug : "mvn install"
{{/maven}}
{{#gradle}}
build-cmd-run : "gradle build"
test-cmd : "gradle build"
build-cmd-debug : "gradle build"
{{/gradle}}

run-cmd : "server run"
debug-cmd : "server debug"
stop-cmd : "server stop"