build-cmd : "mvn install"
# build-cmd : "gradle build"
run-test-cmd: "mvn install"
# run-test-cmd: "gradle build"
run-app-cmd : ["server", "run"]
debug-app-cmd : ["server", "debug"]
stop-app-cmd : ["server", "stop"]
tools-dockerfile : Dockerfile-tools
tools-dockerfile-location: .
run-dockerfile : Dockerfile-run
run-dockerfile-location : .
container-port-map : ["9080:9080", "9443:9443"]
container-debug-port-map : ["9080:9080", "9443:9443", "7777:7777"]
